### ISSUE TITLE
Recover awsacfg resource

### ISSUE THREAD

**Issue by anusha94** [nirmata/kyverno-aws-adapter#58]
**Steps to reproduce**
1. I (accidentally) delete `awsacfg` resource using `kubectl delete`
2. To recover the deleted `awsacfg`, I delete the adapter pod so that when the pod is recreated, it recreates the `awsacfg` resource as well

**Current behavior**
Deleting the adapter pod only recreates the pod, but not `awsacfg` resource. The only way to recover `awsacfg` resource is to do a `helm uninstall` and `helm install` again

**Expected outcome**
Deleting the adapter pod recreates the pod and also `awsacfg` resource

**Comment by kbeniwal** [comment]
Fixed by #61.
